name: New feature proposal / 新功能请求
description: Propose a new feature to be added to GKD
labels: ['enhancement: pending triage']
body:
  - type: markdown
    attributes:
      value: |
        感谢您对该项目的兴趣，并花点时间填写此功能请求报告
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 一些验证
      description: 在提交问题之前，请确保您完成以下操作
      options:
        - label: 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
          required: true
        - label: GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
          required: true
        - label: 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
          required: true
        - label: 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
          required: true
        - label: 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: |
        新功能描述
      description: |
        例如: 我希望在 GKD 中的什么页面添加什么功能, 以及这个功能的作用是什么\
        或者在规则定义中添加某个字段, 以及这个字段的作用是什么\
        请使用准确的描述, 否则你的问题将会被直接关闭
    validations:
      required: true
